CREATE LOGIN [FlxAdmin] WITH PASSWORD=N'YourPassword', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [FlxAdmin] ENABLE
GO
CREATE LOGIN [FlxReader] WITH PASSWORD=N'YourPassword', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [FlxReader] ENABLE
GO
CREATE LOGIN [FlxWriter] WITH PASSWORD=N'YourPassword', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [FlxWriter] ENABLE
GO