--CUSTOM TABLES--
SELECT * FROM TB_EQUIPMENT_CERTIFICATE
SELECT * FROM TB_EQUIPMENT_INTEGRATION_TRACTIAN
SELECT * FROM TB_LOG
SELECT * FROM TB_LOG_ENTITY_MODULE
SELECT * FROM TB_LOG_ENTITY_TYPE
SELECT * FROM TB_WEIGH_LINE_EXTENSION
SELECT * FROM TB_WEIGH_LINE_DETAIL_EXTENSION
SELECT * FROM CHECK_LIST_HISTORY_EXTENSION
SELECT * FROM WIP_ORDER_CAGE
SELECT * FROM TB_QUALITY_RECON_QUEUE
SELECT * FROM TB_PARAMETER
STATUS_TABLES

--CUSTOM VIEWS
SELECT * FROM GRD_VW_GET_JDE_ORDERS
SELECT * FROM GRD_VW_GET_ORGANIZATIONAL_TREE
SELECT * FROM SCALE_REGISTER
SELECT * FROM GRD_VW_GET_CAGE_ITEMS

--CUSTOM PROCEDURES
GRD_SP_CREATE_PRODUCT
GRD_SP_GET_JDE_ORDER_ITEM